#PBS -N BananaGonality
#PBS -q hpcc
#PBS -l nodes=1:ppn=16
#PBS -l walltime=96:00:00
#PBS -l mem=96GB
#PBS -m abe -M ks33@williams.edu
#PBS -o banana_results
#PBS -e banana_error

echo ""
echo “***Ignore Warnings for access to tty***”
echo “”
echo -n “Changing to directory… ”
cd $PBS_O_WORKDIR
echo “”
echo “Our List of nodes:”
echo “”
cat $PBS_NODEFILE
echo “”
module load python/anaconda3
python ../src/banana_gonality.py 2 7 1
echo -n “Finished program at: ”
date