#PBS -N BananaConjectures
#PBS -q hpcc
#PBS -l nodes=1:ppn=64
#PBS -l walltime=72:00:00
#PBS -l mem=96GB
#PBS -m abe -M ks33@williams.edu

echo ""
echo “***Ignore Warnings for access to tty***”
echo “”
echo -n “Changing to directory… ”
cd $PBS_O_WORKDIR
echo “”
echo “Our List of nodes:”
echo “”
cat $PBS_NODEFILE
echo “”
module load python/anaconda3
python ../src/banana.py 2 6 2 conj
echo -n “Finished program at: ”
date